name: SpaceMarket Backend CI/CD

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - back/*         
    exclude:
      - front/*

pr:
  branches:
    include:
      - main
  paths:
    include:
      - back/*

pool: Newpool

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build Maven Project
    steps:
    - task: Maven@4
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'back/pom.xml'     
        goals: 'clean package -DskipTests'
        javaHomeOption: 'Path'     
        jdkDirectory: '/Library/Java/JavaVirtualMachines/jdk-25.jdk/Contents/Home'   
    - task: CopyFiles@2
      displayName: 'Copy JAR to artifact staging directory'
      inputs: 
        SourceFolder: '$(System.DefaultWorkingDirectory)/back/target'
        Contents: |
          *.jar
          !*-plain.jar
        TargetFolder: $(Build.ArtifactStagingDirectory) 
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: spacemarket-back

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Deploy to Azure Web App
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download build artifacts'
      inputs:
        buildType: 'current'
        artifactName: 'spacemarket-back'
        downloadPath: '$(Pipeline.Workspace)'
    - task: AzureWebApp@1
      displayName: 'Deploy Spacemarket Back'
      inputs:
        azureSubscription: 'azure-service-connection' 
        appType: 'webApp' 
        appName: 'spacemarket'
        package: '$(Pipeline.Workspace)/spacemarket-back/*.jar'